### ISSUE TITLE
update v2.3.0

### ISSUE THREAD

**Issue by morgeek** [morgeek/eau_grand_lyon_component#6]
Puisque vous m'avez suggéré de voir pourquoi problème x ou y et que j'ai réouvert le projet.

J'ai fait quelques fix, il y a eu un changement dans HA donc fix de @painteau merged par @hufon.
Icone : @yoyodsl.
J'ai exploré de nouveau leurs endpoints.
J'ai prompté et j'ai sorti une nouvelle version avec un mode expérimental pour leurs API 2026.
Pleins de possibilités futures.
J'ai fait un mail pour demander l'utilisation de leur logo et savoir si cela ne gênait pas les devs de faire des call régulièrement...

J'attends vos retours si problème.

**Comment by yoyodsl** [comment]
Hello Morgeek, merci pour les modifs ;)
Voici mes retours : 
- La mise à jour casse HACS... j'ai réussi à le récupérer avec une sauvegarde d'hier mais pas cool. C'est un gros problème !
  Pour info : j'ai testé deux fois...
- Les entité apparaissent mais pas toutes sont actives.
- Les icones ne changent pas.

Bonne soirée.

**Comment by morgeek** [comment]
Comment ça casse HACS ?
Je l'ai testé chez moi via HACS avant de push sur GitHub. 
Des logs de l'info ?

Chez moi non plus toutes les entités n'apparaissent pas , ça dépend sans doute du type de compteur.
j'ai modifié le fichier hacs.json et le manifest qui étaient malformé peut être que c'était cela.

Dis moi si c'est toujours cassé chez toi? Heureusement que tu avais une sauvegarde ...

**Comment by yoyodsl** [comment]
Toute l'intégration HACS ne fonctionne plus : voici un extrait des logs que j'ai donné à Gemini : 

info: service s6rc-oneshot-runner: starting

s6-rc: info: service s6rc-oneshot-runner successfully started

s6-rc: info: service fix-attrs: starting

s6-rc: info: service fix-attrs successfully started

s6-rc: info: service legacy-cont-init: starting

s6-rc: info: service legacy-cont-init successfully started

s6-rc: info: service legacy-services: starting

services-up: info: copying legacy longrun home-assistant (no readiness notification)

s6-rc: info: service legacy-services successfully started

2026-04-23 20:22:31.786 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration battery_sim which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2026-04-23 20:22:31.787 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration eau_grand_lyon which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2026-04-23 20:22:31.788 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration watchman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2026-04-23 20:22:31.788 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration huesyncbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2026-04-23 20:22:31.789 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration solcast_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2026-04-23 20:22:31.789 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hass_dyson which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2026-04-23 20:22:31.789 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration atmofrance which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2026-04-23 20:22:31.789 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2026-04-23 20:22:31.790 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration gazdebordeaux which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2026-04-23 20:22:31.790 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration toshiba_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2026-04-23 20:22:31.790 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2026-04-23 20:22:35.367 WARNING (MainThread) [custom_components.eau_grand_lyon.api] [EXPÉRIMENTAL] Nouvelles URLs auth échouées (URL de login non trouvée (404): https://agence.eaudugrandlyon.com/auth/externe/authentification) → fallback legacy

2026-04-23 20:22:37.775 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Gaz de Bordeaux - Compte (johann.peters@free.fr)' for gazdebordeaux integration could not authenticate: 403, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url='https://lifeapi.gazdebordeaux.fr/login_check'

2026-04-23 20:22:37.814 CRITICAL (MainThread) [custom_components.hacs] <HacsData restore> ['str' object has no attribute 'items'] Restore Failed!

Traceback (most recent call last):

  File "/config/custom_components/hacs/utils/data.py", line 222, in restore

    self.async_restore_repository(entry, repo_data)

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^

  File "/config/custom_components/hacs/utils/data.py", line 307, in async_restore_repository

    repository.repository_manifest = HacsManifest.from_dict(

                                     ~~~~~~~~~~~~~~~~~~~~~~^

        repository_data.get("manifest") or repository_data.get("repository_manifest") or {}

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    )

    ^

  File "/config/custom_components/hacs/repositories/base.py", line 246, in from_dict

    for k, v in manifest.items()

                ^^^^^^^^^^^^^^

AttributeError: 'str' object has no attribute 'items'

2026-04-23 20:22:37.822 ERROR (MainThread) [custom_components.hacs] HACS is disabled - restore

2026-04-23 20:22:37.981 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'eau_grand_lyon' doesn't specify mean_type when calling async_import_statistics at custom_components/eau_grand_lyon/coordinator.py, line 727: async_add_external_statistics(self.hass, metadata, stats). This will stop working in Home Assistant 2026.11, please create a bug report at https://github.com/morgeek/ha-eau-grand-lyon/issues

2026-04-23 20:22:38.045 ERROR (ImportExecutor_0) [homeassistant] Error doing job: Task exception was never retrieved (task: None)

Traceback (most recent call last):

  File "/config/custom_components/gazdebordeaux/coordinator.py", line 115, in _async_update_data

    await self.api.async_login()

  File "/config/custom_components/gazdebordeaux/gazdebordeaux.py", line 48, in async_login

    token = await response.json()

            ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 188, in json

    return await super().json(*args, loads=loads, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.14/site-packages/aiohttp/client_reqrep.py", line 756, in json

    raise ContentTypeError(

    ...<7 lines>...

    )

aiohttp.client_exceptions.ContentTypeError: 403, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url='https://lifeapi.gazdebordeaux.fr/login_check'



The above exception was the direct cause of the following exception:



Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 769, in __async_setup_with_context

    result = await component.async_setup_entry(hass, self)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/config/custom_components/gazdebordeaux/__init__.py", line 18, in async_setup_entry

    await coordinator.async_config_entry_first_refresh()

  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 319, in async_config_entry_first_refresh

    await self._async_config_entry_first_refresh()

  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 342, in _async_config_entry_first_refresh

    await self._async_refresh(

    ...<3 lines>...

    )

  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 426, in _async_refresh

    self.data = await self._async_update_data()

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/config/custom_components/gazdebordeaux/coordinator.py", line 117, in _async_update_data

    raise ConfigEntryAuthFailed from err

homeassistant.exceptions.ConfigEntryAuthFailed: 403, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=iso-8859-1', url='https://lifeapi.gazdebordeaux.fr/login_check'



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1280, in _async_init_reauth

    result = await hass.config_entries.flow.async_init(

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    ...<9 lines>...

    )

    ^

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1493, in async_init

    flow, result = await self._async_init(flow_id, handler, context, data)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1556, in _async_init

    result = await self._async_handle_step(flow, flow.init_step, data)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 479, in _async_handle_step

    self._raise_if_step_does_not_exist(flow, step_id)

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 572, in _raise_if_step_does_not_exist

    raise UnknownStep(

        f"Handler {flow.__class__.__name__} doesn't support step {step_id}"

    )

**Comment by yoyodsl** [comment]
Et réponse de Gemini : 

Salut ! Le grand classique de la mise à jour qui en fait planter une autre... Pas de panique, tes logs sont très clairs et on va réparer ça.

Le problème ne vient pas directement du code de l'intégration Eau du Grand Lyon, mais plutôt du fait que la mise à jour a corrompu le fichier de sauvegarde interne de HACS au moment de l'écriture.

L'erreur critique est celle-ci :
AttributeError: 'str' object has no attribute 'items'

Concrètement, au démarrage, HACS lit son fichier de cache (qui liste tous tes dépôts). Il s'attend à trouver une structure de données (un dictionnaire JSON) pour un des dépôts, mais il tombe sur une simple chaîne de caractères texte. Ne sachant pas quoi en faire, HACS plante par sécurité et se désactive.

Voici la solution pour tout remettre en ordre.

🛠️ Comment réparer HACS
Il faut forcer HACS à recréer son fichier de cache corrompu. Cela ne supprimera pas tes intégrations déjà installées.

Ouvre ton gestionnaire de fichiers sur Home Assistant (l'add-on File editor ou Studio Code Server, ou via Samba/SSH).

Rends-toi dans ton dossier /config/.

Ouvre le dossier caché nommé .storage/.

Note : Si tu utilises "File editor", il faut parfois cliquer sur la roue crantée en haut à droite et décocher "Hide hidden files" pour voir le dossier .storage.

Cherche le fichier nommé hacs.repositories.

Supprime ce fichier (ou renomme-le en hacs.repositories.bak si tu veux jouer la sécurité absolue).

Redémarre Home Assistant.

Au redémarrage, HACS va scanner tes dossiers, se reconnecter à GitHub et recréer ce fichier proprement au propre. Il devrait réapparaître dans ton menu de gauche en quelques minutes.

Eau du Grand Lyon (Avertissements) : L'intégration a du mal avec la nouvelle URL d'authentification et bascule sur l'ancienne méthode ("fallback legacy"). Ça fonctionne pour l'instant. Il y a aussi un message pour prévenir que le développeur de l'intégration doit mettre à jour son code (le mean_type) avant la version 2026.11 de Home Assistant, sinon elle cessera de fonctionner l'année prochaine. Rien d'urgent pour toi de ce côté-là.

**Comment by yoyodsl** [comment]
Le problème c'est que j'ai fais la manip deux fois donc je ne crois pas bien aux fichiers corrompus par hasard...

J'ai tenté de réparer HACS avec suppression de fichier et en lignes de commandes...
Ca a fonctionné partiellement mais plus aucuns de mes dépôts n'étaient liées dans HACS.
D'après Gemini, ils allaient se reconstruire tout seul en scannant Github. J'ai redémarré plusieurs fois et attendu sans résultat.
D'où la restauration de la sauvegarde auto de ce matin.
Ensuite ,j'ai retenté l'expérience une seconde fois (vu que je n'avais plus rien à perdre) ==>résultat identique : re casse d'HACS. Voilà.
Bon dans l'histoire, j'ai perdu toutes mes stats du jour mais c'est pas bien grave ;)
Du coup, là je tourne sur ta version d'hier soir :)

**Comment by morgeek** [comment]
Ok je check ce problème ce WE. Merci pour le retour ! Je vais creuser le pourquoi.

**Comment by morgeek** [comment]
@yoyodsl  
je viens de sortir une version corrigée qui règle plusieurs problemes qui pouvaient faire planter le chargement du plugin (notamment une erreur d'import dans le calendrier et les diags). 
Quand tu voudras retenter, prends bien la dernière version et pas celle de HACS qui n'est pas à jour pour l'instant ! 

Concernant HACS
J'ai revu le hacs.json et le manifest.json c'est aussi ici que ça déconnait.
Les deux fichiers sont maintenant alignés sur la même version HA minimale (2024.4.0), et le manifest.json est passé en version 2.4.0. 
Des incohérences entre ces deux fichiers pouvaient mettre KO HACS lors de la résolution des dépendances et de la validation du dépôt. (Sorry)
Donc si tu retentes l'install depuis HACS avec la dernière version du dépôt lorsque ce sera en phase avec celle-ci, ça devrait se passer nettement mieux. Tiens moi au courant.

**Comment by yoyodsl** [comment]
Salut Morgeek,

Merci pour ton retour et pour le débogage ;).
Plusieurs questions de newb :) :
Faut d'abord que je fasse la mise à jour en manuelle ? Dans tous les cas ?
Ou j'attends de la faire via HACS... Histoire de voir si tout se passe bien ? Et dans ce cas là, quand penses-tu qu'elle sera à jour sur le store ?
Pourrais-tu également, mettre les numéros de version sur HACS lors du téléchargement stp ? Car pour l'instant on a que des numéros de dépôt indigestes. :)

**Comment by morgeek** [comment]
@yoyodsl tu as tout ce qu'il faut dans cette release! 
je viens de la faire sur HACS c'est a jour de mon coté et pas de crash pour moi.

**Comment by yoyodsl** [comment]
Un grand merci pour tes corrections et tes améliorations et à Claude aussi ;).

Voici mon retour :  

- Maj via HACS OK ==> Version 2.4.0 affichée ==> Nickel ==> HACS pas cassé :) Ouf (j'avais fait une sauvegarde avant :))
- Icones ce sont toujours les tiennes mais ca ne me gêne pas. Ca prend 2sec à remettre "les vrais". 
- Sympa toutes les nouvelles entités (avec le mode hybride).
- Pour info, voici celle qui remonte chez moi et celle qui ne remonte pas. (Je ne sais pas si la remontée dépend du compteur ou de la migration des comptes utilisateurs sur la nouvelle API... Peut-être que tu as une idée sur la question...

<img width="292" height="1174" alt="Image" src="https://github.com/user-attachments/assets/6b06383b-9da4-46ab-8701-c0cca9546dcb" />

<img width="339" height="1148" alt="Image" src="https://github.com/user-attachments/assets/f4780924-2a39-4eb9-b353-3d06699aebc1" />

**Comment by yoyodsl** [comment]
Ce qui serait vraiment top c'est que les consos journalières remontent...
Tu les vois avec ton compteur sur leur site ?

<img width="2129" height="897" alt="Image" src="https://github.com/user-attachments/assets/748ce105-a3e1-4a1d-b25c-af8c33ca64a8" />

**Comment by morgeek** [comment]
Leurs API c'est en cours de dev chez eux je pense ou alors je ne fais pas les choses correctement. 
Les données sont bien liées à ton compte.
On repasse régulièrement en mode legacy au login, tu peux vérifier dans les logs.

La conso journaliere je ne l'ai pas chez moi! La c'est Claude qui m'a suggéré mais en réalité j'ai 0 visu avec mon compte, je sais que l'entité existe mais je ne choppe rien.

**Comment by hufon** [comment]
Pour info, de mon côté, je suis resté focus sur le besoin de remontée journalière.
Je n'ai pas intégré les dernière modifs sur mon fork https://github.com/hufon/HA-Plugin-pour-Eau-du-Grand-Lyon , mais j'ai un truc qui marche pas trop mal

<img width="1626" height="744" alt="Image" src="https://github.com/user-attachments/assets/be1552d5-ce14-47fc-81d5-bde741bf5526" />

**Comment by morgeek** [comment]
salut @hufon, le truc c'est que je n'ai pas le compteur compatible pour avoir le retour d'info.
Puis je piquer ton code pour l'intégrer vu que ça semble marcher chez toi ? Tu veux collaborer sur le meme projet ou garder ton fork? j'avoue je fais le bourrin avec l'IA maintenant le dev assisté est devenu plus simple et moins rigoureux dans les process !

moi j'ai que des message compteur incompatible avec conso journalière.

@yoyodsl j'ai que une conso journalière simulé et constante chaque jour.

**Comment by yoyodsl** [comment]
Bonjour à tous les deux,

Merci pour vos retours et le dev.

J'avoue qu'une seule et unique intégration serait plutôt top... 
@morgeek : J'aime bien les entités que tu as ajouté dans la 2.4.0.
@hufon : top pour la conso journalière (si vous pouviez jumeler vos codes avec Morgeek ;))

@morgeek : Il semble y avoir une erreur de calcul incohérence :

Gemini a analysé (sur ma demande) : 

Sur ta capture d'écran précédente, on voyait une carte "Évolution annuelle" à -317.52 €. En regardant le sensor.eau_du_grand_lyon_economie_vs_n_1, on comprend enfin le bug de calcul de l'intégration :

consommation_n1_m3: 11 (Ta consommation d'un seul mois l'an dernier)

consommation_actuelle_m3: 109 (Ta consommation annuelle complète de cette année)

Le développeur a fait une petite erreur de variable : son code compare la consommation de ton mois précédent avec ton année entière actuelle, ce qui donne une différence aberrante. C'est une excellente information à remonter sur son GitHub (morgeek).

**Comment by morgeek** [comment]
@yoyodsl Je test une nouvelle version pour les corrections de calcul et récupérer les données quotidienne, mais quoi que je fasse c'est KO chez moi. Si @hufon est ok pour devenir collaborateur ou qu'il m'autorise a récupérer son code, aucun problème pour merge son code.

**Comment by hufon** [comment]
Je suis ok bien sur pour que vous repreniez mon code... mais j'ai un peu peur qu'on ait un peu divergé je pourrais essayer de me rebase sur votre version

**Comment by morgeek** [comment]
Merci @hufon, Je raccroche les wagons avec ce que vous avez fait et je push une version 2.5.0 (stable !)
@yoyodsl prêt a tester le compteur journalier ?

**Comment by yoyodsl** [comment]
Bonsoir à tous les deux,

Merci pour les MAJ le dev et pour le code commun ;)

Je viens de passer en 2.8. Voici les entités qui remontent avec mon abonnement ; il y a en a une qui ne remontent plus : Économie potentielle.

L'index journalier ne semble pas fonctionner... :( ;)

<img width="327" height="1043" alt="Image" src="https://github.com/user-attachments/assets/b391d235-4b5a-47bc-9756-2ab9ea791304" />

<img width="382" height="1169" alt="Image" src="https://github.com/user-attachments/assets/9c96e41c-43c5-454f-97bf-e2923f9d2c18" />

<img width="485" height="661" alt="Image" src="https://github.com/user-attachments/assets/b405dcc6-b3d9-4f47-8831-1dabdd34462a" />

**Comment by hufon** [comment]
Je vais rebasculer sur votre version, pour voir si ça marche toujours...
